
import CarCarousel from "@/components/carsCarousel/CarCarousel";
import Htag from "@/components/Htag/Htag";
import ContactForm from "@/components/contactForm/ContactForm";
import {Ri24HoursFill} from "@react-icons/all-files/ri/Ri24HoursFill";
import Timeline from "@/components/timeline/Timeline";
import Advantages from "@/components/advantages/Advantages";
import type {Metadata} from "next";
import Partners from "@/components/partners/Partners";
import Map from "@/components/map/Map";
import About from "@/components/about/About";

export const metadata: Metadata = {
    title: {
        absolute: 'my-next',
        template: "%s | my-next",
    },
    description: "Generated by create next app",
};

export default function Home() {

    return <>
        <div className='cont-left grid grid-cols-[40%_auto] gap-10 my-10'>
            <div className='flex flex-col gap-4'>
                <Htag className='font-extrabold text-4xl mb-0' tag='h1'>Ваш груз — наша забота: точность и скорость
                    гарантированы</Htag>
                <div className='flex items-end gap-6'>
                    <div className='text-[#0D8DD3] text-[20px] font-extrabold'>Курьерская доставка для
                        интернет-магазинов
                    </div>
                    <Ri24HoursFill size={40}/>
                </div>
                <ContactForm/>
            </div>
            <CarCarousel/>
        </div>
        <Advantages/>
        <div className='m-auto'>
            <Timeline/>
        </div>
        <Partners />
        <Map />
        <About />
    </>
}
